[package]
name = "mset"
version = "0.0.1"
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"
license="Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
