[package]
name = "mset"
version = "0.0.1"
descroption = "A mset / multiset / bag implementation"
keyword = ["mset", "multiset", "bag", "counter", "collection"]
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"
license="MIT/Apache-2.0"
