version: 2
jobs:
  "x86_64-unknown-linux-gnu":
    docker:
      - image: cimg/rust:1.40.0
    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build:
    jobs:
      #- "i686-apple-darwin"
      #- "i686-pc-windows-gnu"
      #- "i686-pc-windows-msvc"
      #- "i686-unknown-linux-gnu"
      #- "x86_64-apple-darwin"
      #- "x86_64-pc-windows-gnu"
      #- "x86_64-pc-windows-msvc"
      - "x86_64-unknown-linux-gnu"