version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.40.0
    steps:
      - checkout
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test